### ISSUE TITLE
Same member is adding multiple times in members

### ISSUE THREAD

**Issue by bluetoothfx** [alim1496/realtime-chat-mern#3]
## Issue Description

When I try to back from a webpage and come back to same chat room (without leaving chat room). 

## Expected Behavior

User should not add if user is already present in that room.

## Actual Behavior

User keeps adding in the menu.
![image](https://user-images.githubusercontent.com/5376786/221418785-066d6e9b-aef5-4b87-bbdf-db2ca0d6d061.png)

## Steps to Reproduce

1. Login into the application.
2. Go to a chat room
3. Press browser back button
4. Click on the room again
5. Check the available members list

## Environment

- Operating System: Windows 11
- Browser: Google Chrome, version 91.0.4472.124

## Additional Information

None

**Comment by alim1496** [comment]
fixed in 86820e23a6c78aed87b064027c5603ef3602df2d
