### ISSUE TITLE
Scroll view is not showing when number of chat message is high

### ISSUE THREAD

**Issue by bluetoothfx** [alim1496/realtime-chat-mern#4]
## Issue Description

When I try to scroll latest message the scroll view is completely out from screen.
![image](https://user-images.githubusercontent.com/5376786/221419515-c303be2c-2cab-43a9-855c-40528a81d128.png)

## Expected Behavior

Scroll view should show.

## Actual Behavior

Scroll view is hidden.

## Steps to Reproduce

1. Login to chat application
2. Enter any chat room which has lots of chat messages

## Environment

- Operating System: Windows 11
- Browser: Google Chrome, version 91.0.4472.124

## Additional Information

If user continue to use the application over time this issue will appear.

**Comment by alim1496** [comment]
Fixed in ea5784ffa61a8ce419cdaf53ef674a82083c97cd
