### ISSUE TITLE
Too large payload is accepted.

### ISSUE THREAD

**Issue by bluetoothfx** [alim1496/realtime-chat-mern#6]
## Issue Description
Too large payload is accepted.

![image](https://user-images.githubusercontent.com/5376786/221619840-4a4dc3d1-48ca-4349-83f7-b9a1226cffe6.png)

## Expected Behavior
There should be limit for each chunk of message.

## Actual Behavior
Allowing user to send large amount of data. In case of limit cross there is no user notification what is
going wrong.

## Steps to Reproduce
- Login into the application.
- Go to a chat room
- Paste large text

## Environment
Operating System: Windows 11
Browser: Google Chrome, version 91.0.4472.124

## Additional Information
- This can be solved with multiple way. You can limit data and disable send.
- You can trim message and always allow user to send without restricting user to send.

**Comment by alim1496** [comment]
fixed in b50447abde112edfecf3e1607ed0d4682451da94
