### ISSUE TITLE
UX is breaking in case of good number of user

### ISSUE THREAD

**Issue by bluetoothfx** [alim1496/realtime-chat-mern#8]
## Issue Description
If there is large number of user in one room then UI is breaking. At least there should have some limit 
or need to handle in a way so that no UI breaks.

![image](https://user-images.githubusercontent.com/5376786/221622405-4fae3f36-161b-4035-bba8-681de6148358.png)

![image](https://user-images.githubusercontent.com/5376786/221622466-e066fadc-3d5d-4071-b8b9-65ffc040979b.png)

**Comment by alim1496** [comment]
fixed in be15023628af25f191ef16f08a675b9c68011acc
